apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-k8s-apimessage
  name: docker-k8s-apimessage
spec:
  replicas: 4
  selector:
    matchLabels:
      app: docker-k8s-apimessage
  template:
    metadata:
      name: docker-k8s-apimessage-deployment
      labels:
        app: docker-k8s-apimessage
    spec:
      containers:
      - image: luizcssoares/apirestmessage
        name: docker-k8s-apimessage
        ports:
        - containerPort: 8088                
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-k8s-apimessage
  name: docker-k8s-apimessage-service
spec:
  ports:
    - port: 88
      targetPort: 8088
  selector:
    app: docker_k8s-apimessage
  type: LoadBalancer
